# Python Numpy
- Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

##  Creating a Numpy Array

In [2]:
import numpy as np

In [23]:
## one dim array
scalar=np.array(3)
arr1D=np.array([1,2,3,4])
print(arr1D)

## datatypes of Arrays
arr11=np.array([1,2,3,4], dtype=np.float32)
print(arr11)

## two dimensional array
arr2D=np.array([[1,2],[3,4],[5,6]])
print()
print(arr2D)

## multiple dimensional array

arr3D=np.array([[[1,2],[4,5]],[[6,7],[8,9]]])
print()
print('3d: ', arr3D)
## shape of arrary
print('2d shape:', arr2D.shape)
print(arr3D.shape)
print(arr11.shape)
r, c=arr2D.shape
r1,c1,d1=arr3D.shape
print(r,c)
## Check how many dimensions the arrays have:
print(arr3D.ndim)
print(scalar.ndim)
print(arr11.ndim)

[1 2 3 4]
[1. 2. 3. 4.]

[[1 2]
 [3 4]
 [5 6]]

3d:  [[[1 2]
  [4 5]]

 [[6 7]
  [8 9]]]
2d shape: (3, 2)
(2, 2, 2)
(4,)
3 2
3
0
1


### Convert Python List to numpy Arrays

In [19]:
ll=[3,4,5]
ll2d=[[3,4,5],[6,7,8]]
arr12=np.asarray(ll)
arr13=np.array(ll2d)
print(arr12)
print(arr13.shape)

[3 4 5]
(2, 3)


In [22]:
# convert numpy array to list
arr20=np.array([3,4,5])
lst=arr20.tolist()
print(type(lst))

<class 'list'>


In [33]:
arr6D=np.array([10,12],ndmin=6)
print(arr6D)
print(arr6D.shape)
print(arr6D.ndim)

[[[[[[10 12]]]]]]
(1, 1, 1, 1, 1, 2)
6


In [39]:
## create an array of zeros 
zeros2D=np.zeros(shape=(3,4))
print(zeros2D)
## create an array of ones
ones3D=np.ones((4,2,5))
print(ones3D)

## create identity array
identity2D=np.eye(4)
print(identity2D)

# zeros_like used to return an array of similar shapes and sizes with values of elements 
#of array replaced with zeros.
zeros_Like=np.zeros_like(ones3D)
print(zeros_Like.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 2, 5)


In [42]:
 ## np.arange

seq=np.arange(2,10,2)  
print(seq)
    
## a = np.arange(3).reshape((3, 1))

[2 4 6 8]


## Access Array Elements
- Array indexing is the same as accessing an array element.

- You can access an array element by referring to its index number.

- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [52]:
arr1=np.array([1,2,3,4,5])
arr2=np.arange(15)
print(arr2)
print(arr2[::2])
print(arr2[:4:2])
print(arr2[5::])
print(arr2[5:])
print(arr2[::-1])
# access to element in 2D array
arr2D=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr1[-1])
print(arr1[0:4])

## Negative Indexing

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  2  4  6  8 10 12 14]
[0 2]
[ 5  6  7  8  9 10 11 12 13 14]
[ 5  6  7  8  9 10 11 12 13 14]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
5
[1 2 3 4]


## Slicing in python means taking elements from one given index to another given index.

- We pass slice instead of index like this: [start:end].

- We can also define the step, like this: [start:end:step].

- If we don't pass start its considered 0

- If we don't pass end its considered length of array in that dimension

- If we don't pass step its considered 1

In [64]:
arr2D=np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr2D1=np.array([[1,2,3,4,5], [6,7,8,9,10],[16,17,18,19,110]])
print(arr2D[:,1])
print(arr2D[0,1])
## print 8
print(arr2D[1,2])
print(arr2D[1,:])
print(arr2D1[0,:])
print()
print(arr2D1[:,[0,2]])
print()
print(arr2D1[:,2::2])


[2 7]
2
8
[ 6  7  8  9 10]
[1 2 3 4 5]

[[ 1  3]
 [ 6  8]
 [16 18]]

[[  3   5]
 [  8  10]
 [ 18 110]]


In [13]:
## Return every other element from the entire array:
xs=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
xs[4::]




array([ 5,  6,  7,  8,  9, 10, 11, 12])

## COPY

## Reshaping arrays

In [19]:



# Unknown Dimension (-1)


## Flattening the arrays
arr10 = np.array([[1, 2, 3], [4, 5, 6]])
print
# method 1:


# metnod 2 (ravel)




[1 2 3 4 5 6]


In [20]:
# # 


arr12 = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr12:
  print(x)



[1 2 3]
[4 5 6]


## concatenate two arrays

In [23]:
a1=np.array([1,3])
a2=np.array([10,30])


[ 1  3 10 30]


In [ ]:
# Join two 2-D arrays along rows (axis=1): np.concatenate((arr1, arr2), axis=1)




## Joining Arrays Using Stack Functions np.stack((arr1, arr2), axis=1)
 

    

#Stacking Along Rows


# Stacking Along Columns

## Random Numbers in NumPy

In [83]:
arr100=np.random.rand(10,2)
print(arr100)
arr200=np.random.randint(-20, 100,size=(4,4))
print(arr200)

#arrR=np.random.randint(200,size=(3,4))


## np.random.random


## x = random.choice([3, 5, 7, 9], size=(3, 5))

##print(x)

[[0.7166922  0.2543734 ]
 [0.3025695  0.77925832]
 [0.06006672 0.93133024]
 [0.92367965 0.45953541]
 [0.06592582 0.95086027]
 [0.83191604 0.57472937]
 [0.14044968 0.35045365]
 [0.40298248 0.65549844]
 [0.01420475 0.6355697 ]
 [0.91459778 0.94807317]]
[[  5  48  99  40]
 [ 79 -20  13  62]
 [ 66  11  96  -6]
 [ 98  -2  71 -10]]


In [86]:
def createMatrix(m=10,n=10):
    return np.random.randint(100,size=(m,n))
arr300=createMatrix(5,5)
print(arr300)
                

[[88 40 14 99 62]
 [54 82 22 44 23]
 [31 52 41 42 69]
 [72 79 33 89 74]
 [99 95  4 37 11]]


## np.random.seed()
Seed function is used to save the state of a random function, so that it can generate same random numbers on multiple executions of the code on the same machine or on different machines (for a specific seed value). The seed value is the previous value number generated by the generator. For the first time when there is no previous value, it uses current system time.

In [109]:
np.random.seed(0)
np.random.randint(low = 1, high = 10, size = 50)

array([5, 6, 1, 4, 2, 5, 5, 5, 1, 1, 9, 5, 7, 4, 4, 3, 2, 3, 2, 4, 5, 2,
       2, 1, 8, 9, 5, 4, 6, 7, 4, 3, 9, 2, 5, 1, 9, 4, 6, 6, 2, 8, 9, 7,
       5, 8, 4, 6, 4, 7])

## Arithmetic Operations
Input arrays for performing arithmetic operations such as add(), subtract(), multiply(), and divide() 

#### NumPy matrix multiplication can be done by the following three methods.

- multiply(): element-wise matrix multiplication.
- matmul(): matrix product of two arrays.
- dot(): dot product of two arrays.

## Normal Distribution
The Normal Distribution is one of the most important distributions.

It is also called the Gaussian Distribution after the German mathematician Carl Friedrich Gauss.

It fits the probability distribution of many events, eg. IQ Scores, Heartbeat etc.

Use the random.normal() method to get a Normal Data Distribution.

It has three parameters:

loc - (Mean) where the peak of the bell exists.

scale - (Standard Deviation) how flat the graph distribution should be.

size - The shape of the returned array.

